# Generated by Django 6.1 on 2026-08-10 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurisdictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=16)),
                ('scope', models.CharField(max_length=40)),
                ('sqft', models.PositiveIntegerField()),
                ('timeline', models.CharField(max_length=32)),
                ('addons', models.JSONField(default=dict)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('addon_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='jurisdictions.state')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
