# Generated by Django 6.1 on 2026-08-10 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_projecttype_bar_pct_projecttype_body_projecttype_h1_and_more'),
        ('jurisdictions', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('project_type', models.CharField(max_length=16)),
                ('scope', models.CharField(max_length=40)),
                ('sqft', models.PositiveIntegerField()),
                ('timeline', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('choosing_architect', 'Choosing architect'), ('underway', 'Underway'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='choosing_architect', max_length=20)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('next_action', models.CharField(blank=True, max_length=120)),
                ('architect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='architect_projects', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='projects.estimate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('project_type_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='catalog.projecttype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='jurisdictions.state')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('tag', models.CharField(blank=True, max_length=20)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('rate_label', models.CharField(blank=True, max_length=20)),
                ('rate_display', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted by architect'), ('declined', 'Declined by architect'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn')], default='proposed', max_length=12)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['-score'],
                'unique_together': {('project', 'architect')},
            },
        ),
    ]
