# Generated by Django 6.1 on 2026-08-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='estimate',
            name='goal',
            field=models.CharField(default='design', max_length=16),
        ),
        migrations.AddField(
            model_name='estimate',
            name='quote',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
