# Generated by Django 6.1 on 2026-08-10 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('complexity_score', models.PositiveSmallIntegerField()),
                ('region', models.CharField(max_length=20)),
                ('largest_city', models.CharField(blank=True, max_length=40)),
                ('architect_count', models.CharField(blank=True, help_text='Display value, e.g. "140+"', max_length=16)),
                ('intro', models.TextField(blank=True)),
                ('body1', models.TextField(blank=True)),
                ('body2', models.TextField(blank=True)),
                ('permit_steps', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('county', models.CharField(blank=True, max_length=60)),
                ('architect_count', models.CharField(blank=True, max_length=16)),
                ('intro', models.TextField(blank=True)),
                ('body1', models.TextField(blank=True)),
                ('body2', models.TextField(blank=True)),
                ('permit_facts', models.JSONField(blank=True, default=list)),
                ('service_areas', models.JSONField(blank=True, default=list)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='jurisdictions.state')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
    ]
