# Generated by Django 6.1 on 2026-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('term', models.CharField(max_length=80, unique=True)),
                ('href', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'popular searches',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchIndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Services', 'Services'), ('Project types', 'Project types'), ('Cities', 'Cities'), ('Guides', 'Guides'), ('Case studies', 'Case studies'), ('Pages', 'Pages')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('keywords', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'search index entries',
                'ordering': ['category', 'title'],
            },
        ),
    ]
