# Generated by Django 6.1 on 2026-08-11 01:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='kind',
            field=models.CharField(choices=[('dynamic_fixed_quote', 'Fixed price'), ('hourly', 'Hourly')], max_length=24),
        ),
    ]
