# Generated by Django 6.1 on 2026-08-14 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_milestone_paid_at_alter_engagement_fee_percent_and_more'),
        ('projects', '0003_estimate_answers_estimate_goal_estimate_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(fields=('project', 'provider'), name='unique_engagement_per_project_provider'),
        ),
    ]
