# Generated by Django 6.1 on 2026-08-11 01:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepolicy',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled')], default='active', max_length=12)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=8)),
                ('seats', models.PositiveSmallIntegerField(default=1)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('gateway_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('card_label', models.CharField(blank=True, max_length=40)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('open', 'Open'), ('failed', 'Failed')], default='paid', max_length=8)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('gateway_ref', models.CharField(blank=True, max_length=120)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payments.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('standard', 'Recruiting pages & onboarding'), ('pricing-page', 'Expert pricing page')], default='standard', max_length=20)),
                ('key', models.SlugField(max_length=32)),
                ('name', models.CharField(max_length=40)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, help_text='Per month, billed annually', max_digits=8, null=True)),
                ('per_unit', models.CharField(blank=True, help_text="e.g. ' / seat'", max_length=24)),
                ('project_ceiling', models.CharField(blank=True, max_length=60)),
                ('metro_coverage', models.CharField(blank=True, max_length=60)),
                ('pursuit_limit', models.CharField(blank=True, max_length=60)),
                ('fits', models.CharField(blank=True, max_length=160)),
                ('points', models.JSONField(blank=True, default=list)),
                ('cta_label', models.CharField(blank=True, max_length=48)),
                ('is_recommended', models.BooleanField(default=False)),
                ('gateway_price_id', models.CharField(blank=True, help_text='Stripe price id', max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'sort_order'],
                'unique_together': {('group', 'key')},
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='payments.subscriptionplan'),
        ),
    ]
