# Generated by Django 6.1 on 2026-08-10 08:05

import apps.core.storages
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_projecttype_bar_pct_projecttype_body_projecttype_h1_and_more'),
        ('jurisdictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('typical_rate', models.CharField(blank=True, max_length=32)),
                ('licensure_tag', models.CharField(blank=True, max_length=20)),
                ('requires_license', models.BooleanField(default=False)),
                ('requires_onsite', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchitectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('headshot', models.ImageField(blank=True, upload_to='providers/headshots/')),
                ('based_in', models.CharField(blank=True, max_length=80)),
                ('remote_ok', models.BooleanField(default=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('typical_turnaround', models.CharField(blank=True, max_length=40)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('accepting_work', models.BooleanField(default=True)),
                ('business_entity', models.CharField(blank=True, max_length=40)),
                ('w9_on_file', models.BooleanField(default=False)),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1)),
                ('onboarding_status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('in_review', 'Credential review'), ('approved', 'Approved · live'), ('rejected', 'Rejected')], default='in_progress', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('projects_delivered', models.PositiveIntegerField(default=0)),
                ('on_time_rate', models.PositiveSmallIntegerField(default=0)),
                ('avg_response', models.CharField(blank=True, max_length=16)),
                ('firm_name', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('years_licensed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('role_label', models.CharField(blank=True, max_length=80)),
                ('engagement_mode', models.CharField(choices=[('fixed', 'Fixed quote'), ('hourly', 'Hourly'), ('both', 'Both')], default='both', max_length=10)),
                ('travel_radius_mi', models.PositiveSmallIntegerField(default=35)),
                ('stamp_jurisdictions', models.JSONField(blank=True, default=list, help_text='City/county chips, e.g. Oakland, Alameda County')),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('licensed_states', models.ManyToManyField(blank=True, related_name='%(class)s_providers', to='jurisdictions.state')),
                ('project_types', models.ManyToManyField(blank=True, related_name='architects', to='catalog.projecttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('architect_license', 'Architect license'), ('pe_license', 'PE license'), ('ncarb', 'NCARB record'), ('eo_insurance', 'E&O insurance'), ('certification', 'Certification'), ('business_registration', 'Business registration (EIN)'), ('w9', 'W-9')], max_length=24)),
                ('number', models.CharField(blank=True, max_length=60)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('coverage_amount', models.CharField(blank=True, max_length=20)),
                ('document', models.FileField(blank=True, storage=apps.core.storages.private_storage, upload_to='credentials/%Y/%m/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded · ready to verify'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='uploaded', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('issuing_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='jurisdictions.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('headshot', models.ImageField(blank=True, upload_to='providers/headshots/')),
                ('based_in', models.CharField(blank=True, max_length=80)),
                ('remote_ok', models.BooleanField(default=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('typical_turnaround', models.CharField(blank=True, max_length=40)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('accepting_work', models.BooleanField(default=True)),
                ('business_entity', models.CharField(blank=True, max_length=40)),
                ('w9_on_file', models.BooleanField(default=False)),
                ('onboarding_step', models.PositiveSmallIntegerField(default=1)),
                ('onboarding_status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('in_review', 'Credential review'), ('approved', 'Approved · live'), ('rejected', 'Rejected')], default='in_progress', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('projects_delivered', models.PositiveIntegerField(default=0)),
                ('on_time_rate', models.PositiveSmallIntegerField(default=0)),
                ('avg_response', models.CharField(blank=True, max_length=16)),
                ('studio_name', models.CharField(blank=True, max_length=120)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('software', models.JSONField(blank=True, default=list)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('pricing_mode', models.CharField(choices=[('hourly', 'Hourly'), ('per_deliverable', 'Per deliverable'), ('both', 'Both')], default='hourly', max_length=16)),
                ('onsite_radius_mi', models.PositiveSmallIntegerField(default=40)),
                ('disciplines', models.ManyToManyField(blank=True, related_name='experts', to='providers.discipline')),
                ('licensed_states', models.ManyToManyField(blank=True, related_name='%(class)s_providers', to='jurisdictions.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('image', models.ImageField(blank=True, upload_to='providers/portfolio/')),
                ('title', models.CharField(max_length=120)),
                ('meta', models.CharField(blank=True, max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_name', models.CharField(max_length=80)),
                ('reviewer_role', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
