# Generated by Django 6.1 on 2026-08-17 05:24

import apps.core.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectprofile',
            name='headshot',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='providers/headshots/'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='headshot',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='providers/headshots/'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='providers/portfolio/'),
        ),
    ]
