# Generated by Django 6.1 on 2026-08-10 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('sub', models.CharField(blank=True, max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=78, max_digits=6)),
                ('asbuilt_per_sf', models.DecimalField(decimal_places=2, default=0.25, max_digits=5)),
                ('asbuilt_minimum', models.DecimalField(decimal_places=2, default=2500, max_digits=8)),
                ('per_sheet', models.DecimalField(decimal_places=2, default=30, max_digits=6)),
                ('stamp_fee', models.DecimalField(decimal_places=2, default=1500, max_digits=8)),
                ('rush_pct', models.PositiveSmallIntegerField(default=25)),
            ],
            options={
                'verbose_name': 'Drafting pricing config',
            },
        ),
        migrations.CreateModel(
            name='EstimateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_base', models.FloatField(default=3.2)),
                ('rate_coeff', models.FloatField(default=5.3)),
                ('rate_decay_sqft', models.FloatField(default=2600)),
                ('round_to', models.PositiveSmallIntegerField(default=50)),
                ('multiplier_floor', models.FloatField(default=1.05)),
                ('multiplier_span', models.FloatField(default=0.35)),
                ('range_pct', models.PositiveSmallIntegerField(default=8)),
            ],
            options={
                'verbose_name': 'Estimate engine config',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('key', models.SlugField(max_length=20, unique=True)),
                ('tag', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=80)),
                ('blurb', models.TextField(blank=True)),
                ('points', models.JSONField(blank=True, default=list)),
                ('cta_label', models.CharField(blank=True, max_length=64)),
                ('is_recommended', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('group', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=16)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('sub', models.CharField(blank=True, max_length=160)),
                ('price_display', models.CharField(blank=True, max_length=32)),
                ('slot_id', models.CharField(blank=True, max_length=40)),
                ('image_hint', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenderDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('conceptual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('professional', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photoreal', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon key the frontend maps', max_length=40)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('has_detail', models.BooleanField(default=False)),
                ('detail_href', models.CharField(blank=True, max_length=255)),
                ('from_price', models.CharField(blank=True, help_text='e.g. "from $145"', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'service categories',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_display', models.CharField(max_length=32)),
                ('price_unit', models.CharField(blank=True, max_length=40)),
                ('detail_href', models.CharField(blank=True, max_length=255)),
                ('tier', models.CharField(blank=True, choices=[('volume', 'Volume ($50–500)'), ('core', 'Core ($500–5k)'), ('full_project', 'Full-project ($5k+)')], max_length=16)),
                ('requires_stamp', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.servicecategory')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
    ]
