# Generated by Django 6.1 on 2026-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='bar_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='h1',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='includes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='kicker',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='price_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='price_range',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='related',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='short_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='stats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
