# Generated by Django 6.1 on 2026-08-10 07:38

import apps.core.scopes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('label', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('heading', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroCarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('image', models.ImageField(blank=True, upload_to='cms/carousel/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('name', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_key', models.SlugField(max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='cms/slots/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, help_text='Where this image appears', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('menu', models.CharField(choices=[('services', 'Services'), ('projects', 'Projects'), ('locations', 'Locations')], db_index=True, max_length=16)),
                ('heading', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_key', models.CharField(max_length=80, unique=True, validators=[apps.core.scopes.validate_scope])),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.ImageField(blank=True, upload_to='cms/og/')),
                ('canonical', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Page SEO',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('kicker', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('points', models.TextField(blank=True, help_text='One point per line')),
                ('image', models.ImageField(blank=True, upload_to='cms/personas/')),
                ('cta_label', models.CharField(blank=True, max_length=64)),
                ('cta_href', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_banner_enabled', models.BooleanField(default=True)),
                ('promo_banner_text', models.CharField(blank=True, max_length=255)),
                ('promo_banner_cta_label', models.CharField(blank=True, max_length=64)),
                ('promo_banner_cta_href', models.CharField(blank=True, max_length=255)),
                ('trust_bar_enabled', models.BooleanField(default=True)),
                ('hero_media_mode', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel')], default='carousel', max_length=10)),
                ('hero_image', models.ImageField(blank=True, upload_to='cms/hero/')),
                ('hero_video_url', models.URLField(blank=True)),
                ('contact_email_clients', models.EmailField(default='help@architecthire.com', max_length=254)),
                ('contact_email_support', models.EmailField(default='help@architecthire.com', max_length=254)),
                ('contact_email_privacy', models.EmailField(default='privacy@architecthire.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('platform', models.CharField(max_length=32)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('value', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='cms/steps/')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('audience', models.CharField(choices=[('client', 'Client'), ('architect', 'Architect'), ('expert', 'Expert')], default='client', max_length=12)),
                ('photo', models.ImageField(blank=True, upload_to='cms/testimonials/')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrustLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='cms/logos/')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=64)),
                ('href', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('icon', models.CharField(blank=True, help_text='Icon key the frontend maps', max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('label', models.CharField(max_length=80)),
                ('href', models.CharField(max_length=255)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.footercolumn')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('label', models.CharField(max_length=80)),
                ('sublabel', models.CharField(blank=True, max_length=160)),
                ('href', models.CharField(max_length=255)),
                ('price_hint', models.CharField(blank=True, help_text='e.g. $145 or $65/hr', max_length=32)),
                ('is_featured', models.BooleanField(default=False, help_text='Rendered as the featured card')),
                ('image', models.ImageField(blank=True, upload_to='cms/nav/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.navgroup')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
    ]
