# Generated by Django 6.1 on 2026-08-10 07:41

import apps.core.scopes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('key', models.SlugField(max_length=80)),
                ('text', models.TextField(blank=True)),
                ('href', models.CharField(blank=True, help_text='Only for links/buttons', max_length=255)),
            ],
            options={
                'ordering': ['scope', 'key'],
                'unique_together': {('scope', 'key')},
            },
        ),
    ]
