# Generated by Django 6.1 on 2026-08-10 09:03

import apps.core.scopes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_author_blogcategory_casestudycategory_contactmethod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('category_tag', models.CharField(blank=True, max_length=48)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('excerpt', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='cms/case-cards/')),
                ('href', models.CharField(blank=True, max_length=255)),
                ('stat1_value', models.CharField(blank=True, max_length=32)),
                ('stat1_label', models.CharField(blank=True, max_length=64)),
                ('stat2_value', models.CharField(blank=True, max_length=32)),
                ('stat2_label', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstimateTeaserOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('label', models.CharField(max_length=80)),
                ('price_range', models.CharField(max_length=48)),
                ('bar_pct', models.PositiveSmallIntegerField(default=0, help_text='Range bar fill, 0–100')),
                ('includes', models.TextField(blank=True, help_text="One 'What you get' line per row")),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
    ]
