# Generated by Django 6.1 on 2026-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_casecard_estimateteaseroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecard',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='credentialbadge',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='estimateteaseroption',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='faq',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='herocarouselslide',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='persona',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='principle',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='stat',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='step',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='trustlogo',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='usecase',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
        migrations.AddField(
            model_name='valueprop',
            name='group',
            field=models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40),
        ),
    ]
