# Generated by Django 6.1 on 2026-08-11 02:32

import apps.core.scopes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_casecard_group_credentialbadge_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureMatrixRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('scope', models.CharField(db_index=True, max_length=80, validators=[apps.core.scopes.validate_scope])),
                ('group', models.SlugField(blank=True, help_text="Optional section key, e.g. 'earnings' or 'tools'", max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('is_flagship', models.BooleanField(default=False, help_text='Shows the ★ FLAGSHIP chip')),
                ('tier1', models.CharField(choices=[('yes', 'Included'), ('limited', 'Limited'), ('no', 'Not included')], default='no', max_length=8)),
                ('tier2', models.CharField(choices=[('yes', 'Included'), ('limited', 'Limited'), ('no', 'Not included')], default='no', max_length=8)),
                ('tier3', models.CharField(choices=[('yes', 'Included'), ('limited', 'Limited'), ('no', 'Not included')], default='no', max_length=8)),
            ],
            options={
                'verbose_name': 'feature matrix row',
                'verbose_name_plural': 'feature matrix rows',
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
    ]
