# Generated by Django 6.1 on 2026-08-12 04:47

import apps.core.scopes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_featurematrixrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='slot_key',
            field=models.CharField(max_length=120, unique=True, validators=[apps.core.scopes.validate_slot_key]),
        ),
    ]
