# Generated by Django 6.1 on 2026-08-17 05:24

import apps.core.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_mediaasset_slot_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/authors/'),
        ),
        migrations.AlterField(
            model_name='blogcontentblock',
            name='image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/blog/blocks/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/blog/'),
        ),
        migrations.AlterField(
            model_name='casecard',
            name='image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/case-cards/'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='hero_image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/case-studies/'),
        ),
        migrations.AlterField(
            model_name='casestudyimage',
            name='image',
            field=apps.core.images.ProcessedImageField(upload_to='cms/case-studies/gallery/'),
        ),
        migrations.AlterField(
            model_name='herocarouselslide',
            name='image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/carousel/'),
        ),
        migrations.AlterField(
            model_name='inspirationitem',
            name='image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/inspiration/'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/slots/'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/nav/'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_image',
            field=apps.core.images.ProcessedImageField(blank=True, to_format='JPEG', upload_to='cms/og/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/personas/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/hero/'),
        ),
        migrations.AlterField(
            model_name='step',
            name='image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/steps/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/testimonials/'),
        ),
        migrations.AlterField(
            model_name='trustlogo',
            name='image',
            field=apps.core.images.ProcessedImageField(blank=True, upload_to='cms/logos/'),
        ),
    ]
