# Generated by Django 6.1 on 2026-08-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_author_photo_alter_blogcontentblock_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='credit',
            field=models.CharField(blank=True, help_text="Where this image came from. Set automatically for seeded stock photography; left blank for the agency's own work. Clear it when you replace the image.", max_length=255),
        ),
    ]
