# Generated by Django 6.1 on 2026-08-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_mediaasset_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='focal_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='focal_y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='persona',
            name='image_hint',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
