# Generated by Django 6.1 on 2026-08-18 19:53

from django.db import migrations, models

# Domains `manage.py seed` treats as a floor. Mirrors FLOOR_DOMAINS in the seed command.
FLOOR_DOMAINS = ["jurisdictions", "catalog", "cms", "providers", "payments", "content"]


def backfill(apps, schema_editor):
    """A database that already holds seeded content was seeded before this table existed.
    Mark every floor domain as done so the next `seed --all` does not rewrite the owner's
    edits — the very thing this table is for."""
    CopyBlock = apps.get_model("cms", "CopyBlock")
    SeedRun = apps.get_model("cms", "SeedRun")
    if CopyBlock.objects.exists():
        for domain in FLOOR_DOMAINS:
            SeedRun.objects.get_or_create(domain=domain)


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_terms_links_and_collection_hints"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("domain", models.CharField(max_length=40, unique=True)),
                ("seeded_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
